
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paul.oamen
 */
public class POS extends javax.swing.JFrame {

    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtPayMethod = new javax.swing.JComboBox<>();
        jtxtChange = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtnSummerJuice = new javax.swing.JButton();
        jbtnCappuccino = new javax.swing.JButton();
        jbtnOrangeDrinks = new javax.swing.JButton();
        jbtnRawCoffee = new javax.swing.JButton();
        jbtnChocolateDrink = new javax.swing.JButton();
        jbtnCoffee = new javax.swing.JButton();
        jbtnRainbowCake = new javax.swing.JButton();
        jbtnCupCake = new javax.swing.JButton();
        jbtnSpongecake = new javax.swing.JButton();
        jbtnCreamCake = new javax.swing.JButton();
        jbtnIcedCake = new javax.swing.JButton();
        jbtnSummerDrink = new javax.swing.JButton();
        jbtnIceCream = new javax.swing.JButton();
        jbtnCanDrinks = new javax.swing.JButton();
        jbtnChocolateMixed = new javax.swing.JButton();
        jbtnEasyCake = new javax.swing.JButton();
        jbtnNutCream = new javax.swing.JButton();
        jbtnBlackCoffee = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtBarCode = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel7.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, 50));

        jtxtPayMethod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtPayMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jPanel7.add(jtxtPayMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 200, 50));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel7.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 200, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Change");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Payment Method");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Cash");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 450, 190));

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 160, 50));

        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 50));

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton21.setText("Exit");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, 50));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 50));

        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, 50));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 390, 190));

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel9.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, 50));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel9.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 200, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Total");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("SubTotal");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Tax");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel9.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 200, 50));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1340, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 74, 100));

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 74, 100));

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 74, 100));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 74, 100));

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 74, 100));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 74, 100));

        jbtnDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 74, 100));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 74, 100));

        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 74, 100));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 74, 100));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 74, 100));

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 74, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 430));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnSummerJuice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Non_Alcoholic.GIF"))); // NOI18N
        jbtnSummerJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSummerJuiceActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSummerJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, 130));

        jbtnCappuccino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cappuccino.gif"))); // NOI18N
        jbtnCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCappuccinoActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 120, 130));

        jbtnOrangeDrinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SummerSoftDrinks.gif"))); // NOI18N
        jbtnOrangeDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrangeDrinksActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnOrangeDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, 130));

        jbtnRawCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RawCoffee.GIF"))); // NOI18N
        jbtnRawCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRawCoffeeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnRawCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 120, 130));

        jbtnChocolateDrink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee1.GIF"))); // NOI18N
        jbtnChocolateDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChocolateDrinkActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChocolateDrink, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 120, 130));

        jbtnCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee4.GIF"))); // NOI18N
        jbtnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoffeeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 120, 130));

        jbtnRainbowCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RainCake.GIF"))); // NOI18N
        jbtnRainbowCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRainbowCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnRainbowCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 130));

        jbtnCupCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vanilla Cake.gif"))); // NOI18N
        jbtnCupCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCupCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCupCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 130));

        jbtnSpongecake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cake3.GIF"))); // NOI18N
        jbtnSpongecake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSpongecakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSpongecake, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 130));

        jbtnCreamCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Black Forest Cake.gif"))); // NOI18N
        jbtnCreamCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreamCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCreamCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 120, 130));

        jbtnIcedCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AngleCake.GIF"))); // NOI18N
        jbtnIcedCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIcedCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnIcedCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 120, 130));

        jbtnSummerDrink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cocktails.gif"))); // NOI18N
        jbtnSummerDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSummerDrinkActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSummerDrink, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 120, 130));

        jbtnIceCream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icecream.GIF"))); // NOI18N
        jbtnIceCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIceCreamActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnIceCream, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 130));

        jbtnCanDrinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cokeb.gif"))); // NOI18N
        jbtnCanDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCanDrinksActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCanDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 120, 130));

        jbtnChocolateMixed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UltimateCake.GIF"))); // NOI18N
        jbtnChocolateMixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChocolateMixedActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChocolateMixed, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 120, 130));

        jbtnEasyCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomemadeCake.GIF"))); // NOI18N
        jbtnEasyCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEasyCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnEasyCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 120, 130));

        jbtnNutCream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CrazyCoffee.GIF"))); // NOI18N
        jbtnNutCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNutCreamActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnNutCream, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 120, 130));

        jbtnBlackCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee3.GIF"))); // NOI18N
        jbtnBlackCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBlackCoffeeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnBlackCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 790, 430));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 660, 240, 130));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 480, 40, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 280, 380));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP24DlTt", 0, 36)); // NOI18N
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 280, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
       //=============================Function=================================================
       
    public void ItemCost()
    {
        //int sum = 0;
        double sum = 0;
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            //sum = sum + Integer.parseInt(jTable1.getValueAt(i, 2).toString());
            sum =  sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
          
        }
        //jtxtSubTotal.setText(Integer.toString(sum));
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTotal1 *3.9)/100;
        String iTaxTotal = String.format("£ %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("£ %.2f", cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        
        String iTotal = String.format("£ %.2f", cTax + cTotal1);
        jtxtTotal.setText(iTotal); 
        
        String BarCode = String.format("Total is %.2f", cTax + cTotal1);
        jtxtBarCode.setText(BarCode);
       
    }
//==========================================Function================================================
     public void Change()
    {        
        double sum = 0;
        double tax =3.9;        
        double cash = Double.parseDouble(jtxtDisplay.getText());
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum =  sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());            
        }
        double cTax = (sum * tax)/100;
        double cChange = (cash - (sum + cTax));      
        String ChangeGiven = String.format("£ %.2f", cChange);
        jtxtChange.setText(ChangeGiven);     
  
}
    
//=========================================================================== 
    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String Enternumber = jtxtDisplay.getText();   
        
               
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn1.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn1.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
         String Enternumber = jtxtDisplay.getText();   
        
               
        if ( Enternumber == "")
        {
            jtxtDisplay.setText(jbtn2.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn2.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
         String Enternumber = jtxtDisplay.getText();  
              
        if ( Enternumber == "")
        {
            jtxtDisplay.setText(jbtn4.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn4.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String Enternumber = jtxtDisplay.getText();           
               
        if ( Enternumber == "")
        {
            jtxtDisplay.setText(jbtn5.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn5.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
         String Enternumber = jtxtDisplay.getText();   
        
               
        if ( Enternumber == "")
        {
            jtxtDisplay.setText(jbtn6.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn6.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
         String Enternumber = jtxtDisplay.getText();   
        
               
        if ( Enternumber == "")
        {
            jtxtDisplay.setText(jbtn7.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn7.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
         String Enternumber = jtxtDisplay.getText();   
        
               
        if ( Enternumber == "")
        {
            jtxtDisplay.setText(jbtn8.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn8.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String Enternumber = jtxtDisplay.getText();   
        
               
        if ( Enternumber == "")
        {
            jtxtDisplay.setText(jbtn9.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn9.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
         String Enternumber = jtxtDisplay.getText();   
        
               
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn0.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn0.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
         if(! jtxtDisplay.getText().contains("."))
        {
        jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String Enternumber = jtxtDisplay.getText();   
        
               
        if ( Enternumber == "")
        {
            jtxtDisplay.setText(jbtn3.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn3.getText();
             jtxtDisplay.setText(Enternumber);   
                }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
         jtxtDisplay.setText("");
         jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed
private JFrame frame;
    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Point of Sale",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if (jtxtPayMethod.getSelectedItem().equals("Cash"))
            {
                Change();               
            }
            else
            {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
            }
        
        
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        RecordTable.setRowCount(0);
         jtxtChange.setText("");
                jtxtDisplay.setText("");
                jtxtTax.setText("");
                jtxtSubTotal.setText("");
                jtxtTotal.setText("");
                jtxtBarCode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnCupCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCupCakeActionPerformed
        //int PriceOfItem = 210;  
        double PriceOfItem = 2.10;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cup Cake","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnCupCakeActionPerformed

    private void jbtnBlackCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBlackCoffeeActionPerformed
        double PriceOfItem = 1.70;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cream Cake","1",PriceOfItem});
        
        ItemCost();
    }//GEN-LAST:event_jbtnBlackCoffeeActionPerformed

    private void jbtnSpongecakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSpongecakeActionPerformed
        double PriceOfItem = 2.75;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Sponge Cake","1",PriceOfItem});
        
        ItemCost();
    }//GEN-LAST:event_jbtnSpongecakeActionPerformed

    private void jbtnOrangeDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrangeDrinksActionPerformed
       double PriceOfItem = 1.20;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Orange Drinks","1",PriceOfItem});
        
        ItemCost();
    }//GEN-LAST:event_jbtnOrangeDrinksActionPerformed

    private void jbtnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoffeeActionPerformed
        double PriceOfItem = 0.90;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Coffee","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnCoffeeActionPerformed

    private void jbtnCreamCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreamCakeActionPerformed
        double PriceOfItem = 2.78;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cream Cake","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnCreamCakeActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();          
             
        int  RemoveItem =  jTable1.getSelectedRow();                      
        if (RemoveItem >= 0)
        {
        model.removeRow(RemoveItem);  
        }   
        
        ItemCost();
        
        if (jtxtPayMethod.getSelectedItem().equals("Cash"))
            {
                Change();               
            }
        
        String Enternumber = jtxtDisplay.getText();
                       
        if (Enternumber == "" && jtxtPayMethod.getSelectedItem().equals("Cash"))
        {      
            
                jtxtChange.setText("");
                jtxtDisplay.setText("");
            }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jbtnRainbowCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRainbowCakeActionPerformed
        double PriceOfItem = 3.40;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rainbow Cake","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnRainbowCakeActionPerformed

    private void jbtnCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCappuccinoActionPerformed
      double PriceOfItem = 2.57;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cappuccino","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnCappuccinoActionPerformed

    private void jbtnCanDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCanDrinksActionPerformed
        double PriceOfItem = 0.57;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Can Drinks","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnCanDrinksActionPerformed

    private void jbtnChocolateDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChocolateDrinkActionPerformed
         double PriceOfItem = 2.30;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chocolate Drink","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnChocolateDrinkActionPerformed

    private void jbtnIcedCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIcedCakeActionPerformed
       double PriceOfItem = 2.90;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Iced Cake","1",PriceOfItem});        
        ItemCost(); 
    }//GEN-LAST:event_jbtnIcedCakeActionPerformed

    private void jbtnSummerDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSummerDrinkActionPerformed
        double PriceOfItem = 3.20;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Summer Drink","1",PriceOfItem});        
        ItemCost(); 
    }//GEN-LAST:event_jbtnSummerDrinkActionPerformed

    private void jbtnIceCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIceCreamActionPerformed
        double PriceOfItem = 2.95;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Cream","1",PriceOfItem});        
        ItemCost(); 
    }//GEN-LAST:event_jbtnIceCreamActionPerformed

    private void jbtnSummerJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSummerJuiceActionPerformed
         double PriceOfItem = 2.90;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Summer Juice","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnSummerJuiceActionPerformed

    private void jbtnChocolateMixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChocolateMixedActionPerformed
        double PriceOfItem = 2.99;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chocolate Mixed","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnChocolateMixedActionPerformed

    private void jbtnEasyCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEasyCakeActionPerformed
        double PriceOfItem = 2.95;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Easy Cake","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnEasyCakeActionPerformed

    private void jbtnNutCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNutCreamActionPerformed
        double PriceOfItem = 3.75;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Nut Cream","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnNutCreamActionPerformed

    private void jbtnRawCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRawCoffeeActionPerformed
        double PriceOfItem = 3.95;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Raw Coffee","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnRawCoffeeActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
         MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBlackCoffee;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCanDrinks;
    private javax.swing.JButton jbtnCappuccino;
    private javax.swing.JButton jbtnChocolateDrink;
    private javax.swing.JButton jbtnChocolateMixed;
    private javax.swing.JButton jbtnCoffee;
    private javax.swing.JButton jbtnCreamCake;
    private javax.swing.JButton jbtnCupCake;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEasyCake;
    private javax.swing.JButton jbtnIceCream;
    private javax.swing.JButton jbtnIcedCake;
    private javax.swing.JButton jbtnNutCream;
    private javax.swing.JButton jbtnOrangeDrinks;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRainbowCake;
    private javax.swing.JButton jbtnRawCoffee;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSpongecake;
    private javax.swing.JButton jbtnSummerDrink;
    private javax.swing.JButton jbtnSummerJuice;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JComboBox<String> jtxtPayMethod;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
